### ISSUE TITLE
ERROR: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by zerofo** [nICEnnnnnnnLee/action-gitee-release#1]
报错了, 帮忙看看 谢谢
```
- name: gitee release
      id: create_release
      uses: nicennnnnnnlee/action-gitee-release@v1.0.1
      with:
        gitee_owner: zerofo
        gitee_repo: ATM_ZxNs
        gitee_token: ${{ secrets.gitee_token }}
        gitee_tag_name: master
        gitee_release_name: Test v1.0.0
        gitee_release_body: "Updated: ${{ github.event.repository.updated_at }} "
        gitee_target_commitish: master
        gitee_file_name: ZxNs_ATM.zip
        gitee_file_path: ./output/
```

```
Run nicennnnnnnlee/action-gitee-release@v1.0.1
  with:
    gitee_owner: zerofo
    gitee_repo: ATM_ZxNs
    gitee_token: ***
    gitee_tag_name: master
    gitee_release_name: Test v1.0.0
    gitee_release_body: Updated: [2](https://github.com/zerofo/NX_creator/actions/runs/10190099993/job/28189260926#step:6:2)024-08-01T01:04:[3](https://github.com/zerofo/NX_creator/actions/runs/10190099993/job/28189260926#step:6:3)7Z 
    gitee_target_commitish: master
    gitee_file_name: ZxNs_ATM.zip
    gitee_file_path: ./output/
Run pip install -r requirements.txt
  pip install -r requirements.txt
  python gitee_release.py
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    gitee_owner: zerofo
    gitee_repo: ATM_ZxNs
    gitee_token: ***
    gitee_tag_name: master
    gitee_release_name: Test v1.0.0
    gitee_release_body: Updated: 202[4](https://github.com/zerofo/NX_creator/actions/runs/10190099993/job/28189260926#step:6:4)-08-01T01:04:37Z 
    gitee_target_commitish: master
    gitee_files: 
    gitee_file_name: ZxNs_ATM.zip
    gitee_file_path: ./output/
    gitee_release_id: 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Error: Process completed with exit code 1.
```
